### ISSUE TITLE
What happens when its scrolled back 

### ISSUE THREAD

**Issue by kamarajuPrathi** [flexyford/impagination#50]
I am new to this library  , i like the way you mentioned . Quick question i scrolled down like 10 pages (100 records appox) so when i scroll up , will you hold that data in state ? Or will we call api when we scroll up . My case i will have more than 10000+ records

**Comment by cowboyd** [comment]
Hello!

It will invoke your callback when you scroll up if the records have not yet been loaded. If they *have* been loaded (and have not been unloaded by your unload hook) then it will not be called.

**Comment by kamarajuPrathi** [comment]
Do we have an example with react web application

**Comment by cowboyd** [comment]
Here is an example using the imagination component in a real project https://github.com/folio-org/ui-eholdings/blob/e98238ab0eaed917238d59919fc9459229bed178/src/components/query-list/query-list.js#L70

**Comment by kamarajuPrathi** [comment]
@cowboyd Thank you , can i make it run locally , i see this issue when i am trying to run locally


```
> @folio/eholdings@1.5.0 start /Users/kprat1/Downloads/ui-eholdings-e98238ab0eaed917238d59919fc9459229bed178
> stripes serve

/Users/kprat1/Downloads/ui-eholdings-e98238ab0eaed917238d59919fc9459229bed178/node_modules/@folio/stripes-cli/lib/cli/stripes-config-middleware.js:18
async function readStripesConfigStdin() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at lazy (/Users/kprat1/Downloads/ui-eholdings-e98238ab0eaed917238d59919fc9459229bed178/node_modules/import-lazy/index.js:2:51)
    at Object.get (/Users/kprat1/Downloads/ui-eholdings-e98238ab0eaed917238d59919fc9459229bed178/node_modules/import-lazy/index.js:10:11) 
```
